[env:heltec_mesh_node_t114]
platform = nordicnrf52
board = heltec_mesh_node_t114
framework = arduino
monitor_speed = 115200

build_flags =
    -Ivariants/nrf52840/heltec_mesh_node_t114
    -I${platformio.packages_dir}/framework-arduinoadafruitnrf52/libraries/SPI
    -I${platformio.packages_dir}/framework-arduinoadafruitnrf52/libraries/Wire

board_build.variant = heltec_mesh_node_t114
board_build.variants_dir = variants/nrf52840

lib_extra_dirs =
    ${platformio.packages_dir}/framework-arduinoadafruitnrf52/libraries

lib_deps =
    jgromes/RadioLib
    SPI
    Wire

lib_ignore =
    SdFat - Adafruit Fork